services:
  database:
    image: postgis/postgis:18-3.6
    container_name: gtfs-on-time-database
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"

    volumes:
      - gtfs_on_time_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  gtfs_on_time_postgres_data: